2024-06-24 14:39:22,117 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:40]
2024-06-24 14:39:22,754 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:40]
2024-06-24 14:39:25,164 ERROR: DuplicateKeyError: E11000 duplicate key error collection: rbac_db.admin_action_passwords index: user_id_1 dup key: { user_id: null }, full error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: rbac_db.admin_action_passwords index: user_id_1 dup key: { user_id: null }', 'keyPattern': {'user_id': 1}, 'keyValue': {'user_id': None}} [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:911]
2024-06-24 14:54:14,535 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:40]
2024-06-23 21:14:45,626 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 21:15:10,970 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 21:16:09,977 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 21:20:25,037 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 21:20:58,546 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:07:13,717 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:13:22,840 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:15:21,451 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:16:58,298 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:16:58,953 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:24:47,474 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:25:21,736 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:26:05,064 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:26:10,343 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:26:12,488 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:26:22,832 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:28:33,923 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:32:25,874 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:35:51,558 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:45:18,479 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:46:02,963 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:47:44,322 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:47:55,830 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:48:13,289 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 22:59:29,507 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:135]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 530, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-23 22:59:43,406 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:135]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 530, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-23 23:03:01,439 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:35]
2024-06-23 23:05:37,868 ERROR: Unhandled exception: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:135]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-06-23 23:11:44,973 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:36]
2024-06-23 23:12:45,657 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:136]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 533, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-23 23:16:47,282 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:36]
2024-06-23 23:17:53,140 INFO: Application startup [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:38]
2024-06-23 23:19:19,061 ERROR: Unhandled exception: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:138]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 412, in api_login
    csrf_access_token = get_jwt()['csrf']
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
2024-06-23 23:19:24,694 ERROR: Unhandled exception: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:138]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 412, in api_login
    csrf_access_token = get_jwt()['csrf']
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
2024-06-23 23:19:25,704 ERROR: Unhandled exception: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:138]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 412, in api_login
    csrf_access_token = get_jwt()['csrf']
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
2024-06-27 12:36:28,150 INFO: Someone tried to register with username: faker [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:291]
2024-06-27 12:36:28,284 INFO: faker Successfully registered [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:314]
2024-06-27 12:43:42,869 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:44:02,904 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:44:22,895 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:48:26,282 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:48:46,277 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:49:06,291 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:49:36,321 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
2024-06-27 12:49:56,330 ERROR: Unhandled exception: local variable 'cpu_usage' referenced before assignment [in C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py:195]
Traceback (most recent call last):
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Solstxce\scoop\apps\python39\current\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Solstxce\Projects\IBM_Internship_ZT\app.py", line 790, in system_stats
    'cpu_usage': cpu_usage,
UnboundLocalError: local variable 'cpu_usage' referenced before assignment
